version: "2"

run:
  timeout: 3m

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/zigai/zgod

linters:
  enable:
    - asasalint
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - godoclint
    - godot
    - goprintffuncname
    - gosec
    - govet
    - iface
    - ineffassign
    - intrange
    - iotamixing
    - makezero
    - mirror
    - misspell
    - modernize
    - nakedret
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace

  settings:
    errcheck:
      check-type-assertions: true

    exhaustive:
      check:
        - switch
        - map

    gochecksumtype:
      default-signifies-exhaustive: false

    gocognit:
      min-complexity: 20

    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false

    godoclint:
      enable:
        - no-unused-link
        - require-stdlib-doclink

    govet:
      enable-all: true
      disable:
        - fieldalignment
      settings:
        shadow:
          strict: true

    misspell:
      locale: US

    nakedret:
      max-func-lines: 5

    revive:
      rules:
        - name: error-naming
        - name: if-return
        - name: var-naming
        - name: error-strings
        - name: receiver-naming
        - name: indent-error-flow
        - name: superfluous-else
        - name: modifies-parameter
        - name: unreachable-code
          disabled: true
        - name: redefines-builtin-id
          disabled: true

    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx

    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1016
        - -QF1008

    nolintlint:
      allow-no-explanation: [funlen, gocognit, golines]
      require-explanation: true
      require-specific: true

    gosec:
      excludes:
        - G204 # exec.Command from $EDITOR is user-controlled by design
        - G301 # directory perms
        - G302 # file perms
        - G304 # file path from variable

  exclusions:
    warn-unused: true
    presets: []

    rules:
      - source: "TODO"
        linters: [godot]

      - path: "_test\\.go"
        linters:
          - bodyclose
          - errcheck
          - goconst
          - gosec
          - dogsled
          - gocognit
