version: 2
project_name: zgod

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    binary: zgod
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/zigai/zgod/internal/cli.version={{.Version}}
      - -X github.com/zigai/zgod/internal/cli.commit={{.ShortCommit}}
      - -X github.com/zigai/zgod/internal/cli.date={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  abbrev: 7
  format: "[`{{ printf \"%.7s\" .SHA }}`](https://github.com/zigai/zgod/commit/{{ .SHA }}) {{ .Message }}"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: zigai
    name: zgod
  draft: false
  prerelease: auto
